apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-alb-demo
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: rollouts-alb-demo-canary
      stableService: rollouts-alb-demo-stable
      trafficRouting:
        alb:
          ingress: rollouts-alb-demo-ingress
          servicePort: 80
      steps:
      - setWeight: 5
      - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-alb-demo
  template:
    metadata:
      labels:
        app: rollouts-alb-demo
    spec:
      containers:
      - name: rollouts-alb-demo
        image: plentiful/rollouts-demo:yellow
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
